version: "3.3"
services:
  app:
    build: .
    image: book_downloader
    env_file:
      - secrets/app.env
      - secrets/db.env
    environment:
      - HOME_FOLDER=./tmp
      - DB_HOST=db
    restart: always
  db:
    image: postgres:13.3
    restart: always
    container_name: book_downloader_db
    env_file:
      - secrets/db.env
    ports:
      - "5432:5432"